// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.80.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

part 'bridge_definitions.freezed.dart';

abstract class Rustdesk {
  Stream<String> startGlobalEventStream(
      {required String appType, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartGlobalEventStreamConstMeta;

  Future<void> stopGlobalEventStream({required String appType, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStopGlobalEventStreamConstMeta;

  Future<void> hostStopSystemKeyPropagate(
      {required bool stopped, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHostStopSystemKeyPropagateConstMeta;

  int peerGetSessionsCount(
      {required String id, required int connType, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPeerGetSessionsCountConstMeta;

  String sessionAddExistedSync(
      {required String id,
      required UuidValue sessionId,
      required Int32List displays,
      required bool isViewCamera,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionAddExistedSyncConstMeta;

  String sessionAddSync(
      {required UuidValue sessionId,
      required String id,
      required bool isFileTransfer,
      required bool isViewCamera,
      required bool isPortForward,
      required bool isRdp,
      required bool isTerminal,
      required String switchUuid,
      required bool forceRelay,
      required String password,
      required bool isSharedPassword,
      String? connToken,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionAddSyncConstMeta;

  Stream<EventToUI> sessionStart(
      {required UuidValue sessionId, required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionStartConstMeta;

  Stream<EventToUI> sessionStartWithDisplays(
      {required UuidValue sessionId,
      required String id,
      required Int32List displays,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionStartWithDisplaysConstMeta;

  Future<bool?> sessionGetRemember(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetRememberConstMeta;

  Future<bool?> sessionGetToggleOption(
      {required UuidValue sessionId, required String arg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetToggleOptionConstMeta;

  bool sessionGetToggleOptionSync(
      {required UuidValue sessionId, required String arg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetToggleOptionSyncConstMeta;

  Future<String?> sessionGetOption(
      {required UuidValue sessionId, required String arg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetOptionConstMeta;

  Future<void> sessionLogin(
      {required UuidValue sessionId,
      required String osUsername,
      required String osPassword,
      required String password,
      required bool remember,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionLoginConstMeta;

  Future<void> sessionSend2Fa(
      {required UuidValue sessionId,
      required String code,
      required bool trustThisDevice,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSend2FaConstMeta;

  bool sessionGetEnableTrustedDevices(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetEnableTrustedDevicesConstMeta;

  bool willSessionCloseCloseSession(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWillSessionCloseCloseSessionConstMeta;

  Future<void> sessionClose({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCloseConstMeta;

  Future<void> sessionRefresh(
      {required UuidValue sessionId, required int display, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRefreshConstMeta;

  Future<void> sessionTakeScreenshot(
      {required UuidValue sessionId, required int display, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionTakeScreenshotConstMeta;

  Future<String> sessionHandleScreenshot(
      {required UuidValue sessionId, required String action, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionHandleScreenshotConstMeta;

  bool sessionIsMultiUiSession({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionIsMultiUiSessionConstMeta;

  Future<void> sessionRecordScreen(
      {required UuidValue sessionId, required bool start, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRecordScreenConstMeta;

  bool sessionGetIsRecording({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetIsRecordingConstMeta;

  Future<void> sessionReconnect(
      {required UuidValue sessionId, required bool forceRelay, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionReconnectConstMeta;

  Future<void> sessionToggleOption(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionToggleOptionConstMeta;

  Future<void> sessionTogglePrivacyMode(
      {required UuidValue sessionId,
      required String implKey,
      required bool on,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionTogglePrivacyModeConstMeta;

  Future<String?> sessionGetFlutterOption(
      {required UuidValue sessionId, required String k, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetFlutterOptionConstMeta;

  Future<void> sessionSetFlutterOption(
      {required UuidValue sessionId,
      required String k,
      required String v,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetFlutterOptionConstMeta;

  int getNextTextureKey({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetNextTextureKeyConstMeta;

  String getLocalFlutterOption({required String k, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetLocalFlutterOptionConstMeta;

  Future<void> setLocalFlutterOption(
      {required String k, required String v, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetLocalFlutterOptionConstMeta;

  String getLocalKbLayoutType({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetLocalKbLayoutTypeConstMeta;

  Future<void> setLocalKbLayoutType(
      {required String kbLayoutType, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetLocalKbLayoutTypeConstMeta;

  Future<String?> sessionGetViewStyle(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetViewStyleConstMeta;

  Future<void> sessionSetViewStyle(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetViewStyleConstMeta;

  Future<String?> sessionGetScrollStyle(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetScrollStyleConstMeta;

  Future<void> sessionSetScrollStyle(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetScrollStyleConstMeta;

  Future<int?> sessionGetEdgeScrollEdgeThickness(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionGetEdgeScrollEdgeThicknessConstMeta;

  Future<void> sessionSetEdgeScrollEdgeThickness(
      {required UuidValue sessionId, required int value, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionSetEdgeScrollEdgeThicknessConstMeta;

  Future<String?> sessionGetImageQuality(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetImageQualityConstMeta;

  Future<void> sessionSetImageQuality(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetImageQualityConstMeta;

  Future<String?> sessionGetKeyboardMode(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetKeyboardModeConstMeta;

  Future<void> sessionSetKeyboardMode(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetKeyboardModeConstMeta;

  String? sessionGetReverseMouseWheelSync(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetReverseMouseWheelSyncConstMeta;

  Future<void> sessionSetReverseMouseWheel(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetReverseMouseWheelConstMeta;

  String? sessionGetDisplaysAsIndividualWindows(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionGetDisplaysAsIndividualWindowsConstMeta;

  Future<void> sessionSetDisplaysAsIndividualWindows(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionSetDisplaysAsIndividualWindowsConstMeta;

  String? sessionGetUseAllMyDisplaysForTheRemoteSession(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionGetUseAllMyDisplaysForTheRemoteSessionConstMeta;

  Future<void> sessionSetUseAllMyDisplaysForTheRemoteSession(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionSetUseAllMyDisplaysForTheRemoteSessionConstMeta;

  Future<Int32List?> sessionGetCustomImageQuality(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetCustomImageQualityConstMeta;

  bool sessionIsKeyboardModeSupported(
      {required UuidValue sessionId, required String mode, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionIsKeyboardModeSupportedConstMeta;

  Future<void> sessionSetCustomImageQuality(
      {required UuidValue sessionId, required int value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetCustomImageQualityConstMeta;

  Future<void> sessionSetCustomFps(
      {required UuidValue sessionId, required int fps, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetCustomFpsConstMeta;

  Future<int?> sessionGetTrackpadSpeed(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetTrackpadSpeedConstMeta;

  Future<void> sessionSetTrackpadSpeed(
      {required UuidValue sessionId, required int value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetTrackpadSpeedConstMeta;

  Future<void> sessionLockScreen({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionLockScreenConstMeta;

  Future<void> sessionCtrlAltDel({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCtrlAltDelConstMeta;

  Future<void> sessionSwitchDisplay(
      {required bool isDesktop,
      required UuidValue sessionId,
      required Int32List value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSwitchDisplayConstMeta;

  Future<void> sessionHandleFlutterKeyEvent(
      {required UuidValue sessionId,
      required String character,
      required int usbHid,
      required int lockModes,
      required bool downOrUp,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionHandleFlutterKeyEventConstMeta;

  Future<void> sessionHandleFlutterRawKeyEvent(
      {required UuidValue sessionId,
      required String name,
      required int platformCode,
      required int positionCode,
      required int lockModes,
      required bool downOrUp,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionHandleFlutterRawKeyEventConstMeta;

  void sessionEnterOrLeave(
      {required UuidValue sessionId, required bool enter, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionEnterOrLeaveConstMeta;

  Future<void> sessionInputKey(
      {required UuidValue sessionId,
      required String name,
      required bool down,
      required bool press,
      required bool alt,
      required bool ctrl,
      required bool shift,
      required bool command,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionInputKeyConstMeta;

  Future<void> sessionInputString(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionInputStringConstMeta;

  Future<void> sessionSendChat(
      {required UuidValue sessionId, required String text, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendChatConstMeta;

  Future<void> sessionOpenTerminal(
      {required UuidValue sessionId,
      required int terminalId,
      required int rows,
      required int cols,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionOpenTerminalConstMeta;

  Future<void> sessionSendTerminalInput(
      {required UuidValue sessionId,
      required int terminalId,
      required String data,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendTerminalInputConstMeta;

  Future<void> sessionResizeTerminal(
      {required UuidValue sessionId,
      required int terminalId,
      required int rows,
      required int cols,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionResizeTerminalConstMeta;

  Future<void> sessionCloseTerminal(
      {required UuidValue sessionId, required int terminalId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCloseTerminalConstMeta;

  Future<void> sessionPeerOption(
      {required UuidValue sessionId,
      required String name,
      required String value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionPeerOptionConstMeta;

  Future<String> sessionGetPeerOption(
      {required UuidValue sessionId, required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetPeerOptionConstMeta;

  Future<void> sessionInputOsPassword(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionInputOsPasswordConstMeta;

  Future<void> sessionReadRemoteDir(
      {required UuidValue sessionId,
      required String path,
      required bool includeHidden,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionReadRemoteDirConstMeta;

  Future<void> sessionSendFiles(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required String to,
      required int fileNum,
      required bool includeHidden,
      required bool isRemote,
      required bool isDir,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendFilesConstMeta;

  Future<void> sessionSetConfirmOverrideFile(
      {required UuidValue sessionId,
      required int actId,
      required int fileNum,
      required bool needOverride,
      required bool remember,
      required bool isUpload,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetConfirmOverrideFileConstMeta;

  Future<void> sessionRemoveFile(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required int fileNum,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRemoveFileConstMeta;

  Future<void> sessionReadDirToRemoveRecursive(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required bool isRemote,
      required bool showHidden,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionReadDirToRemoveRecursiveConstMeta;

  Future<void> sessionRemoveAllEmptyDirs(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRemoveAllEmptyDirsConstMeta;

  Future<void> sessionCancelJob(
      {required UuidValue sessionId, required int actId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCancelJobConstMeta;

  Future<void> sessionCreateDir(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCreateDirConstMeta;

  Future<String> sessionReadLocalDirSync(
      {required UuidValue sessionId,
      required String path,
      required bool showHidden,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionReadLocalDirSyncConstMeta;

  Future<String> sessionReadLocalEmptyDirsRecursiveSync(
      {required UuidValue sessionId,
      required String path,
      required bool includeHidden,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionReadLocalEmptyDirsRecursiveSyncConstMeta;

  Future<void> sessionReadRemoteEmptyDirsRecursiveSync(
      {required UuidValue sessionId,
      required String path,
      required bool includeHidden,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionReadRemoteEmptyDirsRecursiveSyncConstMeta;

  Future<String> sessionGetPlatform(
      {required UuidValue sessionId, required bool isRemote, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetPlatformConstMeta;

  Future<void> sessionLoadLastTransferJobs(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionLoadLastTransferJobsConstMeta;

  Future<void> sessionAddJob(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required String to,
      required int fileNum,
      required bool includeHidden,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionAddJobConstMeta;

  Future<void> sessionResumeJob(
      {required UuidValue sessionId,
      required int actId,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionResumeJobConstMeta;

  Future<void> sessionRenameFile(
      {required UuidValue sessionId,
      required int actId,
      required String path,
      required String newName,
      required bool isRemote,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRenameFileConstMeta;

  Future<void> sessionElevateDirect(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionElevateDirectConstMeta;

  Future<void> sessionElevateWithLogon(
      {required UuidValue sessionId,
      required String username,
      required String password,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionElevateWithLogonConstMeta;

  Future<void> sessionSwitchSides({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSwitchSidesConstMeta;

  Future<void> sessionChangeResolution(
      {required UuidValue sessionId,
      required int display,
      required int width,
      required int height,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionChangeResolutionConstMeta;

  Future<void> sessionSetSize(
      {required UuidValue sessionId,
      required int display,
      required int width,
      required int height,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetSizeConstMeta;

  Future<void> sessionSendSelectedSessionId(
      {required UuidValue sessionId, required String sid, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendSelectedSessionIdConstMeta;

  Future<List<String>> mainGetSoundInputs({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetSoundInputsConstMeta;

  String mainGetLoginDeviceInfo({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLoginDeviceInfoConstMeta;

  Future<void> mainChangeId({required String newId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainChangeIdConstMeta;

  Future<String> mainGetAsyncStatus({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetAsyncStatusConstMeta;

  Future<String?> mainGetHttpStatus({required String url, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetHttpStatusConstMeta;

  Future<String> mainGetOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetOptionConstMeta;

  String mainGetOptionSync({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetOptionSyncConstMeta;

  Future<String> mainGetError({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetErrorConstMeta;

  bool mainShowOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainShowOptionConstMeta;

  Future<void> mainSetOption(
      {required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetOptionConstMeta;

  Future<String> mainGetOptions({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetOptionsConstMeta;

  String mainGetOptionsSync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetOptionsSyncConstMeta;

  Future<void> mainSetOptions({required String json, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetOptionsConstMeta;

  Future<String> mainTestIfValidServer(
      {required String server, required bool testWithProxy, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainTestIfValidServerConstMeta;

  Future<void> mainSetSocks(
      {required String proxy,
      required String username,
      required String password,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetSocksConstMeta;

  Future<bool> mainGetProxyStatus({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetProxyStatusConstMeta;

  Future<List<String>> mainGetSocks({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetSocksConstMeta;

  Future<String> mainGetAppName({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetAppNameConstMeta;

  String mainGetAppNameSync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetAppNameSyncConstMeta;

  String mainUriPrefixSync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainUriPrefixSyncConstMeta;

  Future<String> mainGetLicense({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLicenseConstMeta;

  Future<String> mainGetVersion({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetVersionConstMeta;

  Future<List<String>> mainGetFav({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetFavConstMeta;

  Future<void> mainStoreFav({required List<String> favs, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainStoreFavConstMeta;

  String mainGetPeerSync({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetPeerSyncConstMeta;

  Future<String> mainGetLanPeers({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLanPeersConstMeta;

  Future<String> mainGetConnectStatus({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetConnectStatusConstMeta;

  Future<void> mainCheckConnectStatus({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCheckConnectStatusConstMeta;

  Future<bool> mainIsUsingPublicServer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsUsingPublicServerConstMeta;

  Future<void> mainDiscover({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainDiscoverConstMeta;

  Future<String> mainGetApiServer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetApiServerConstMeta;

  String mainResolveAvatarUrl({required String avatar, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainResolveAvatarUrlConstMeta;

  Future<void> mainHttpRequest(
      {required String url,
      required String method,
      String? body,
      required String header,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHttpRequestConstMeta;

  String mainGetLocalOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLocalOptionConstMeta;

  bool mainGetUseTextureRender({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetUseTextureRenderConstMeta;

  String mainGetEnv({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetEnvConstMeta;

  void mainSetEnv({required String key, String? value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetEnvConstMeta;

  Future<void> mainSetLocalOption(
      {required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetLocalOptionConstMeta;

  Future<String> mainHandleWaylandScreencastRestoreToken(
      {required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kMainHandleWaylandScreencastRestoreTokenConstMeta;

  String mainGetInputSource({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetInputSourceConstMeta;

  Future<void> mainSetInputSource(
      {required UuidValue sessionId, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetInputSourceConstMeta;

  /// Set cursor position (for pointer lock re-centering).
  ///
  /// # Returns
  /// - `true`: cursor position was successfully set
  /// - `false`: operation failed or not supported
  ///
  /// # Platform behavior
  /// - Windows/macOS/Linux: attempts to move the cursor to (x, y)
  /// - Android/iOS: no-op, always returns `false`
  bool mainSetCursorPosition({required int x, required int y, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetCursorPositionConstMeta;

  /// Clip cursor to a rectangle (for pointer lock).
  ///
  /// When `enable` is true, the cursor is clipped to the rectangle defined by
  /// `left`, `top`, `right`, `bottom`. When `enable` is false, the rectangle
  /// values are ignored and the cursor is unclipped.
  ///
  /// # Returns
  /// - `true`: operation succeeded or no-op completed
  /// - `false`: operation failed
  ///
  /// # Platform behavior
  /// - Windows: uses ClipCursor API to confine cursor to the specified rectangle
  /// - macOS: uses CGAssociateMouseAndMouseCursorPosition for pointer lock effect;
  ///   the rect coordinates are ignored (only Some/None matters)
  /// - Linux: no-op, always returns `true`; use pointer warping for similar effect
  /// - Android/iOS: no-op, always returns `false`
  bool mainClipCursor(
      {required int left,
      required int top,
      required int right,
      required int bottom,
      required bool enable,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainClipCursorConstMeta;

  Future<String> mainGetMyId({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetMyIdConstMeta;

  Future<String> mainGetUuid({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetUuidConstMeta;

  Future<String> mainGetPeerOption(
      {required String id, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetPeerOptionConstMeta;

  String mainGetPeerOptionSync(
      {required String id, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetPeerOptionSyncConstMeta;

  String mainGetPeerFlutterOptionSync(
      {required String id, required String k, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetPeerFlutterOptionSyncConstMeta;

  void mainSetPeerFlutterOptionSync(
      {required String id, required String k, required String v, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetPeerFlutterOptionSyncConstMeta;

  Future<void> mainSetPeerOption(
      {required String id,
      required String key,
      required String value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetPeerOptionConstMeta;

  bool mainSetPeerOptionSync(
      {required String id,
      required String key,
      required String value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetPeerOptionSyncConstMeta;

  Future<void> mainSetPeerAlias(
      {required String id, required String alias, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetPeerAliasConstMeta;

  Future<String> mainGetNewStoredPeers({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetNewStoredPeersConstMeta;

  Future<void> mainForgetPassword({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainForgetPasswordConstMeta;

  Future<bool> mainPeerHasPassword({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainPeerHasPasswordConstMeta;

  Future<bool> mainPeerExists({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainPeerExistsConstMeta;

  Future<void> mainLoadRecentPeers({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadRecentPeersConstMeta;

  Future<String> mainLoadRecentPeersForAb(
      {required String filter, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadRecentPeersForAbConstMeta;

  Future<void> mainLoadFavPeers({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadFavPeersConstMeta;

  Future<void> mainLoadLanPeers({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadLanPeersConstMeta;

  Future<void> mainRemoveDiscovered({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainRemoveDiscoveredConstMeta;

  Future<void> mainChangeTheme({required String dark, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainChangeThemeConstMeta;

  Future<void> mainChangeLanguage({required String lang, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainChangeLanguageConstMeta;

  String mainVideoSaveDirectory({required bool root, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainVideoSaveDirectoryConstMeta;

  Future<void> mainSetUserDefaultOption(
      {required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetUserDefaultOptionConstMeta;

  String mainGetUserDefaultOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetUserDefaultOptionConstMeta;

  Future<String> mainHandleRelayId({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHandleRelayIdConstMeta;

  bool mainIsOptionFixed({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsOptionFixedConstMeta;

  String mainGetMainDisplay({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetMainDisplayConstMeta;

  String mainGetDisplays({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetDisplaysConstMeta;

  Future<void> sessionAddPortForward(
      {required UuidValue sessionId,
      required int localPort,
      required String remoteHost,
      required int remotePort,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionAddPortForwardConstMeta;

  Future<void> sessionRemovePortForward(
      {required UuidValue sessionId, required int localPort, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRemovePortForwardConstMeta;

  Future<void> sessionNewRdp({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionNewRdpConstMeta;

  Future<void> sessionRequestVoiceCall(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRequestVoiceCallConstMeta;

  Future<void> sessionCloseVoiceCall(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionCloseVoiceCallConstMeta;

  String? sessionGetConnToken({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetConnTokenConstMeta;

  Future<void> cmHandleIncomingVoiceCall(
      {required int id, required bool accept, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmHandleIncomingVoiceCallConstMeta;

  Future<void> cmCloseVoiceCall({required int id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmCloseVoiceCallConstMeta;

  Future<void> setVoiceCallInputDevice(
      {required bool isCm, required String device, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetVoiceCallInputDeviceConstMeta;

  Future<String> getVoiceCallInputDevice({required bool isCm, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetVoiceCallInputDeviceConstMeta;

  Future<String> mainGetLastRemoteId({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLastRemoteIdConstMeta;

  Future<void> mainGetSoftwareUpdateUrl({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetSoftwareUpdateUrlConstMeta;

  Future<String> mainGetHomeDir({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetHomeDirConstMeta;

  Future<String> mainGetLangs({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetLangsConstMeta;

  Future<String> mainGetTemporaryPassword({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetTemporaryPasswordConstMeta;

  Future<bool> mainSetPermanentPasswordWithResult(
      {required String password, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kMainSetPermanentPasswordWithResultConstMeta;

  Future<String> mainGetFingerprint({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetFingerprintConstMeta;

  Future<String> cmGetClientsState({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmGetClientsStateConstMeta;

  Future<String?> cmCheckClientsLength({required int length, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmCheckClientsLengthConstMeta;

  Future<int> cmGetClientsLength({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmGetClientsLengthConstMeta;

  Future<void> mainInit(
      {required String appDir,
      required String customClientConfig,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainInitConstMeta;

  Future<void> mainDeviceId({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainDeviceIdConstMeta;

  Future<void> mainDeviceName({required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainDeviceNameConstMeta;

  Future<void> mainRemovePeer({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainRemovePeerConstMeta;

  bool mainHasHwcodec({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasHwcodecConstMeta;

  bool mainHasVram({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasVramConstMeta;

  String mainSupportedHwdecodings({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSupportedHwdecodingsConstMeta;

  Future<bool> mainIsRoot({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsRootConstMeta;

  int getDoubleClickTime({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetDoubleClickTimeConstMeta;

  Future<void> mainStartDbusServer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainStartDbusServerConstMeta;

  Future<void> mainSaveAb({required String json, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSaveAbConstMeta;

  Future<void> mainClearAb({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainClearAbConstMeta;

  Future<String> mainLoadAb({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadAbConstMeta;

  Future<void> mainSaveGroup({required String json, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSaveGroupConstMeta;

  Future<void> mainClearGroup({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainClearGroupConstMeta;

  Future<String> mainLoadGroup({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainLoadGroupConstMeta;

  Future<void> sessionSendPointer(
      {required UuidValue sessionId, required String msg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendPointerConstMeta;

  /// Send mouse event from Flutter to the remote peer.
  ///
  /// # Relative Mouse Mode Message Contract
  ///
  /// When the message contains a `relative_mouse_mode` field, this function validates
  /// and filters activation/deactivation markers.
  ///
  /// **Mode Authority:**
  /// The Flutter InputModel is authoritative for relative mouse mode activation/deactivation.
  /// The server (via `input_service.rs`) only consumes forwarded delta movements and tracks
  /// relative movement processing state, but does NOT control mode activation/deactivation.
  ///
  /// **Deactivation Markers are Local-Only:**
  /// Deactivation markers (`relative_mouse_mode: "0"`) are NEVER forwarded to the server.
  /// They are handled entirely on the client side to reset local UI state (cursor visibility,
  /// pointer lock, etc.). The server does not rely on deactivation markers and should not
  /// expect to receive them.
  ///
  /// **Contract (Flutter side MUST adhere to):**
  /// 1. `relative_mouse_mode` field is ONLY present on activation/deactivation marker messages,
  ///    NEVER on normal pointer events (move, button, scroll).
  /// 2. Deactivation marker: `{"relative_mouse_mode": "0"}` - local-only, never forwarded.
  /// 3. Activation marker: `{"relative_mouse_mode": "1", "type": "move_relative", "x": "0", "y": "0"}`
  ///    - MUST use `type="move_relative"` with `x="0"` and `y="0"` (safe no-op).
  ///    - Any other combination is dropped to prevent accidental cursor movement.
  ///
  /// If these assumptions are violated (e.g., `relative_mouse_mode` is added to normal events),
  /// legitimate mouse events may be silently dropped by the early-return logic below.
  Future<void> sessionSendMouse(
      {required UuidValue sessionId, required String msg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendMouseConstMeta;

  Future<void> sessionRestartRemoteDevice(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRestartRemoteDeviceConstMeta;

  String sessionGetAuditServerSync(
      {required UuidValue sessionId, required String typ, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetAuditServerSyncConstMeta;

  Future<void> sessionSendNote(
      {required UuidValue sessionId, required String note, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSendNoteConstMeta;

  String sessionGetLastAuditNote({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetLastAuditNoteConstMeta;

  Future<void> sessionSetAuditGuid(
      {required UuidValue sessionId, required String guid, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionSetAuditGuidConstMeta;

  String sessionGetAuditGuid({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetAuditGuidConstMeta;

  String sessionGetConnSessionId({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetConnSessionIdConstMeta;

  Future<String> sessionAlternativeCodecs(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionAlternativeCodecsConstMeta;

  Future<void> sessionChangePreferCodec(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionChangePreferCodecConstMeta;

  Future<void> sessionOnWaitingForImageDialogShow(
      {required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionOnWaitingForImageDialogShowConstMeta;

  Future<void> sessionToggleVirtualDisplay(
      {required UuidValue sessionId,
      required int index,
      required bool on,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionToggleVirtualDisplayConstMeta;

  Future<void> sessionPrinterResponse(
      {required UuidValue sessionId,
      required int id,
      required String path,
      required String printerName,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionPrinterResponseConstMeta;

  Future<void> mainSetHomeDir({required String home, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetHomeDirConstMeta;

  String mainGetDataDirIos({required String appDir, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetDataDirIosConstMeta;

  Future<void> mainStopService({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainStopServiceConstMeta;

  Future<void> mainStartService({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainStartServiceConstMeta;

  Future<void> mainUpdateTemporaryPassword({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainUpdateTemporaryPasswordConstMeta;

  Future<bool> mainCheckSuperUserPermission({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCheckSuperUserPermissionConstMeta;

  String mainGetUnlockPin({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetUnlockPinConstMeta;

  String mainSetUnlockPin({required String pin, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetUnlockPinConstMeta;

  Future<void> mainCheckMouseTime({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCheckMouseTimeConstMeta;

  Future<double> mainGetMouseTime({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetMouseTimeConstMeta;

  Future<void> mainWol({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainWolConstMeta;

  Future<void> mainCreateShortcut({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCreateShortcutConstMeta;

  Future<void> cmSendChat(
      {required int connId, required String msg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmSendChatConstMeta;

  Future<void> cmLoginRes(
      {required int connId, required bool res, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmLoginResConstMeta;

  Future<void> cmCloseConnection({required int connId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmCloseConnectionConstMeta;

  Future<void> cmRemoveDisconnectedConnection(
      {required int connId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmRemoveDisconnectedConnectionConstMeta;

  Future<void> cmCheckClickTime({required int connId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmCheckClickTimeConstMeta;

  Future<double> cmGetClickTime({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmGetClickTimeConstMeta;

  Future<void> cmSwitchPermission(
      {required int connId,
      required String name,
      required bool enabled,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmSwitchPermissionConstMeta;

  bool cmCanElevate({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmCanElevateConstMeta;

  Future<void> cmElevatePortable({required int connId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmElevatePortableConstMeta;

  Future<void> cmSwitchBack({required int connId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmSwitchBackConstMeta;

  Future<String> cmGetConfig({required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmGetConfigConstMeta;

  Future<String> mainGetBuildDate({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetBuildDateConstMeta;

  String translate(
      {required String name, required String locale, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kTranslateConstMeta;

  int sessionGetRgbaSize(
      {required UuidValue sessionId, required int display, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetRgbaSizeConstMeta;

  void sessionNextRgba(
      {required UuidValue sessionId, required int display, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionNextRgbaConstMeta;

  void sessionRegisterPixelbufferTexture(
      {required UuidValue sessionId,
      required int display,
      required int ptr,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kSessionRegisterPixelbufferTextureConstMeta;

  void sessionRegisterGpuTexture(
      {required UuidValue sessionId,
      required int display,
      required int ptr,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRegisterGpuTextureConstMeta;

  Future<void> queryOnlines({required List<String> ids, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kQueryOnlinesConstMeta;

  int versionToNumber({required String v, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kVersionToNumberConstMeta;

  Future<bool> optionSynced({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOptionSyncedConstMeta;

  bool mainIsInstalled({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsInstalledConstMeta;

  void mainInitInputSource({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainInitInputSourceConstMeta;

  bool mainIsInstalledLowerVersion({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsInstalledLowerVersionConstMeta;

  bool mainIsInstalledDaemon({required bool prompt, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsInstalledDaemonConstMeta;

  bool mainIsProcessTrusted({required bool prompt, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsProcessTrustedConstMeta;

  bool mainIsCanScreenRecording({required bool prompt, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsCanScreenRecordingConstMeta;

  bool mainIsCanInputMonitoring({required bool prompt, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsCanInputMonitoringConstMeta;

  bool mainIsShareRdp({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsShareRdpConstMeta;

  Future<void> mainSetShareRdp({required bool enable, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetShareRdpConstMeta;

  bool mainGotoInstall({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGotoInstallConstMeta;

  String mainGetNewVersion({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetNewVersionConstMeta;

  bool mainUpdateMe({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainUpdateMeConstMeta;

  Future<void> setCurSessionId({required UuidValue sessionId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetCurSessionIdConstMeta;

  bool installShowRunWithoutInstall({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInstallShowRunWithoutInstallConstMeta;

  Future<void> installRunWithoutInstall({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInstallRunWithoutInstallConstMeta;

  Future<void> installInstallMe(
      {required String options, required String path, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInstallInstallMeConstMeta;

  String installInstallPath({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInstallInstallPathConstMeta;

  String installInstallOptions({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInstallInstallOptionsConstMeta;

  Future<void> mainAccountAuth(
      {required String op, required bool rememberMe, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainAccountAuthConstMeta;

  Future<void> mainAccountAuthCancel({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainAccountAuthCancelConstMeta;

  Future<String> mainAccountAuthResult({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainAccountAuthResultConstMeta;

  Future<void> mainOnMainWindowClose({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainOnMainWindowCloseConstMeta;

  bool mainCurrentIsWayland({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCurrentIsWaylandConstMeta;

  bool mainIsLoginWayland({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainIsLoginWaylandConstMeta;

  bool mainHideDock({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHideDockConstMeta;

  bool mainHasFileClipboard({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasFileClipboardConstMeta;

  bool mainHasGpuTextureRender({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasGpuTextureRenderConstMeta;

  Future<void> cmInit({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCmInitConstMeta;

  /// Start an ipc server for receiving the url scheme.
  ///
  /// * Should only be called in the main flutter window.
  /// * macOS only
  Future<void> mainStartIpcUrlServer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainStartIpcUrlServerConstMeta;

  Future<void> mainTestWallpaper({required int second, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainTestWallpaperConstMeta;

  Future<bool> mainSupportRemoveWallpaper({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSupportRemoveWallpaperConstMeta;

  bool isIncomingOnly({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsIncomingOnlyConstMeta;

  bool isOutgoingOnly({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsOutgoingOnlyConstMeta;

  bool isCustomClient({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsCustomClientConstMeta;

  bool isDisableSettings({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsDisableSettingsConstMeta;

  bool isDisableAb({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsDisableAbConstMeta;

  bool isDisableAccount({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsDisableAccountConstMeta;

  bool isDisableGroupPanel({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsDisableGroupPanelConstMeta;

  bool isDisableInstallation({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsDisableInstallationConstMeta;

  Future<bool> isPresetPassword({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsPresetPasswordConstMeta;

  bool isPresetPasswordMobileOnly({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsPresetPasswordMobileOnlyConstMeta;

  /// Send a url scheme through the ipc.
  ///
  /// * macOS only
  Future<void> sendUrlScheme({required String url, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendUrlSchemeConstMeta;

  Future<void> pluginEvent(
      {required String id,
      required String peer,
      required Uint8List event,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginEventConstMeta;

  Stream<EventToUI> pluginRegisterEventStream(
      {required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginRegisterEventStreamConstMeta;

  String? pluginGetSessionOption(
      {required String id,
      required String peer,
      required String key,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginGetSessionOptionConstMeta;

  Future<void> pluginSetSessionOption(
      {required String id,
      required String peer,
      required String key,
      required String value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginSetSessionOptionConstMeta;

  String? pluginGetSharedOption(
      {required String id, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginGetSharedOptionConstMeta;

  Future<void> pluginSetSharedOption(
      {required String id,
      required String key,
      required String value,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginSetSharedOptionConstMeta;

  Future<void> pluginReload({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginReloadConstMeta;

  void pluginEnable({required String id, required bool v, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginEnableConstMeta;

  bool pluginIsEnabled({required String id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginIsEnabledConstMeta;

  bool pluginFeatureIsEnabled({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginFeatureIsEnabledConstMeta;

  Future<void> pluginSyncUi({required String syncTo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginSyncUiConstMeta;

  Future<void> pluginListReload({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginListReloadConstMeta;

  Future<void> pluginInstall(
      {required String id, required bool b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPluginInstallConstMeta;

  bool isSupportMultiUiSession({required String version, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsSupportMultiUiSessionConstMeta;

  bool isSelinuxEnforcing({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIsSelinuxEnforcingConstMeta;

  String mainDefaultPrivacyModeImpl({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainDefaultPrivacyModeImplConstMeta;

  String mainSupportedPrivacyModeImpls({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSupportedPrivacyModeImplsConstMeta;

  String mainSupportedInputSource({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSupportedInputSourceConstMeta;

  Future<String> mainGenerate2Fa({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGenerate2FaConstMeta;

  Future<bool> mainVerify2Fa({required String code, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainVerify2FaConstMeta;

  bool mainHasValid2FaSync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasValid2FaSyncConstMeta;

  Future<String> mainVerifyBot({required String token, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainVerifyBotConstMeta;

  bool mainHasValidBotSync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainHasValidBotSyncConstMeta;

  String mainGetHardOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetHardOptionConstMeta;

  String mainGetBuildinOption({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetBuildinOptionConstMeta;

  Future<void> mainCheckHwcodec({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainCheckHwcodecConstMeta;

  Future<String> mainGetTrustedDevices({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetTrustedDevicesConstMeta;

  Future<void> mainRemoveTrustedDevices({required String json, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainRemoveTrustedDevicesConstMeta;

  Future<void> mainClearTrustedDevices({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainClearTrustedDevicesConstMeta;

  int mainMaxEncryptLen({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainMaxEncryptLenConstMeta;

  Future<void> sessionRequestNewDisplayInitMsgs(
      {required UuidValue sessionId, required int display, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionRequestNewDisplayInitMsgsConstMeta;

  bool mainAudioSupportLoopback({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainAudioSupportLoopbackConstMeta;

  String mainGetPrinterNames({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetPrinterNamesConstMeta;

  Future<String> mainGetCommon({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetCommonConstMeta;

  String mainGetCommonSync({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainGetCommonSyncConstMeta;

  Future<void> mainSetCommon(
      {required String key, required String value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainSetCommonConstMeta;

  String? sessionGetCommonSync(
      {required UuidValue sessionId,
      required String key,
      required String param,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetCommonSyncConstMeta;

  Future<String?> sessionGetCommon(
      {required UuidValue sessionId,
      required String key,
      required String param,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSessionGetCommonConstMeta;
}

@freezed
sealed class EventToUI with _$EventToUI {
  const factory EventToUI.event(
    String field0,
  ) = EventToUI_Event;
  const factory EventToUI.rgba(
    int field0,
  ) = EventToUI_Rgba;
  const factory EventToUI.texture(
    int field0,
    bool field1,
  ) = EventToUI_Texture;
}
